FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Gallery API

API для работы с галереями Interlike App

## Group Gallery

## Gallery config [/api/v1.0/gallery_config/{cmpNameUrl}/{eventNameUrl}]

+ Parameters
    + cmpNameUrl - cmpNameUrl
    + eventNameUrl - eventNameUrl

### Get config [GET]

+ Response 200 (application/json)
        
    + Attributes (object)

        + logo (string) -  Путь к картинке с логотипом
        + title (string) - Заголовок
        + description (string) -  Описание для галереи
        + photoDescription (string) -  Описание для фотографии
        + header(object) - Настройки для шапки.
            +   bgcolor - цвет фона вида #СССССС
            +   bgimage - ссылка на картинку фона
            +   textcolor - цвет текста вида #СССССС
            +   photosCountTextColor - цвет текста для надписи с количеством фотографий
        
        + fullSizePhoto (object) - Настройки для полноэкранного отображения фотографии.
            +   bgcolor - цвет фона вида #СССССС
            +   bgimage - ссылка на картинку фона
            +   textcolor - цвет текста вида #СССССС
            +   photosCountTextColor - цвет текста для надписи с количеством фотографий
            
        + `sharingButtons` (object) - Список отображаемых кнопок для шаринга в соцсетях.
            + Возможные ключи
                    + `fb`
                    + `vk`
                    + `twitter`
                    + `linkedin`
                    + `pin`
                    + `odnoklassniki`
            + Возможные значения
                    + `image`
                    + `object`
        + `sharingWidget` (array) - Список виджетов для шаринга. Возможные значения:
            + fb, instagram
        + `buttons` (array) - Список функциональных кнопок. Возможные значения:
            + download, copy, html
        + showNavigation (number) - 1 или 0. Если 1, показывать стрелки вперед-назад и кнопку "закрыть"(вернуться в галерею) при отображении фотографии в полноэранном режиме.
        + `showNewFirst` (number) - 1 или 0. Если 1, первыми показывать самые свежие фотографии (LIFO). Если 0 - FIFO.
        + `rootUrl` (string) - Урл сайта с галереей (нужно для корректной работы навигации по галерее в embded-режиме, подробнее в ТЗ).
        + eventStartDt (string) - Дата начала ивента в формате ISO 8601.
        + eventEndDt (string) - Дата окончания ивента в формате ISO 8601.

    + Body
        
            {
                "logo":"http://my.interlikeapp.com/images/uploaded/1470287629317logo_VCOneGoodThing_horizontal_colour_RGB.jpg",
                "title":"VisitCanberra",
                "description":"<p>#visitcanberra</p>",
                "photoDescription":"Experiencing one good thing after another at the Canberra and Region Visitors Centre! #visitcanberra",
                "header" {
                    "bgcolor": "#000000",
                    "bgimage": null,
                    "textcolor": "#FFFFFF",
                    "photosCountTextColor": "#FCFCFC",
                },
                "fullSizePhoto": {
                    "bgcolor": null,
                    "bgimage": null,
                    "textcolor": "#FFFFFF",
                },
                "custom_css": "http://my.interlikeapp.com/bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css",
                "sharingButtons": {
                    "fb": "object",
                    "twitter": "image"},
                "sharingWidgets": ['fb'],
                "buttons": ["download", "html"]
                "showNavigation": 1,
                "showNewFirst": 1,
                "rootUrl": "http://my.interlikeapp.com",
                "eventStartDt": "2018-09-17T14-16-26.386823Z",
                "eventEndDt": "2018-09-17T14-16-26.386823Z"
            }
        
## Gallery Photos [/api/v1.0/gallery/{cmpNameUrl}/{eventNameUrl}{?startDt}{?endDt}{?lastDt}{?limit}{?offset}]

## Get photos [GET]

+ Parameters
    + cmpNameUrl - cmpNameUrl
    + eventNameUrl - eventNameUrl

+ Response 200 (application/json)

    + Attributes (object)
    
        + `filteredCount` (number) - Количество фотографий в соответствии с заданным фильтром без учета лимита. Нужно для отображения общего количества фотографий в шапке.
        + `limitedCount` (number) - Фактическое количество фотографий, которое вернул запрос, с учетом лимита.
        + `items` (array) - Список фотографий
            + id, createDt, url

    + Body

            {
                "filteredCount": 4,
                "limitedCount": 4,
                "items": 
                    [
                        {
                            "_id": "57b3ed87ac8da6856aa40b1e",
                            "createDt": "2016-08-17T04:52:23.095Z",
                            "url": "http://my.interlikeapp.com/published/visitcanberra/57b3ed87ac8da6856aa40b1e.png"
                        },
                        {
                            "_id": "57b51f7eac8da6856aa41844",
                            "createDt": "2016-08-18T02:37:50.065Z",
                            "url": "http://my.interlikeapp.com/published/visitcanberra/57b51f7eac8da6856aa41844.png"
                        },
                        {
                            "_id": "57b51fcaac8da6856aa41850",
                            "createDt": "2016-08-18T02:39:06.942Z",
                            "url": "http://my.interlikeapp.com/published/visitcanberra/57b51fcaac8da6856aa41850.png"
                        },
                        {
                            "_id": "57b51fe9ac8da6856aa41855",
                            "createDt": "2016-08-18T02:39:37.524Z",
                            "url": "http://my.interlikeapp.com/published/visitcanberra/57b51fe9ac8da6856aa41855.png"
                        }
                    ]
            }
        
## Gallery Photo By Id [/api/v1.0/gallery/{photoId}]

## Get photo by Id [GET]

+ Parameters
    + photoId - Id фотографии

+ Response 200 (application/json)

            {
                "_id": "57b51fe9ac8da6856aa41855",
                "createDt": "2016-08-18T02:39:37.524Z",
                "url": "http://my.interlikeapp.com/published/visitcanberra/57b51fe9ac8da6856aa41855.png"
            }
            
## Fb analytics [/api/v1.0/add_fb_share/{photoId}]

## Post new share [POST]

+ Parameters
    + photoId - Id фотографии

+ Response 200 (application/json)